---
title: "Klein"
author: "Esther KLEIN"
format: html
editor: visual
---

## Question 1

```{r message=FALSE, warning=FALSE}
library(readr)
library(here)
courses <- read_csv(here("courses.csv"), show_col_types = FALSE)
```



## Question 2

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(knitr)

courses |> 
  rename(
    course_name = course,
    identifier = course_id,
    number_of_exams = nb_grades
  ) |> 
  arrange(course_name) |> 
  kable()
```

## Question 3 

```{r message=FALSE, warning=FALSE}

students <- read_csv(here("students.csv"),show_col_types = FALSE) |>
  mutate(
    birth_date = as.Date(birth_date),
    sex = factor(sex)
  )

birth_date_class <- class(students$birth_date)
sex_class <- class(students$sex)

students |>
  slice_head(n = 5) |>
  kable()
```

The `birth_date` column of the students data frame is of class `r birth_date_class`.
The `sex` column of the students data frame is of class `r sex_class`.


## Question 4 


```{r message=FALSE, warning=FALSE}
library(readr)

grades <- read_delim(
  "grades.csv",
  delim = "|",
  na = "$",
  show_col_types = FALSE
)


```


## Question 5

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)

students |>
  count(group, name = "nb_students") |>
  ggplot(aes(x = factor(group), y = nb_students)) +
  geom_col() +
  labs(x = "Group", y = "Number of students")
```

## Question 6 

```{r message=FALSE, warning=FALSE}

students |>
  count(group, sex) |>
  ggplot(aes(x = group, y = n, fill = sex)) +
  geom_col()
```


## Question 7

```{r message=FALSE, warning=FALSE}
library(lubridate)

students |>
  mutate(age = time_length(today() - birth_date, unit = "year")) |>
  ggplot(aes(x = age)) +
  labs(x = "Age", y = "Number of students") +
  geom_histogram()
```

## Question 8 

```{r message=FALSE, warning=FALSE}
median_age <- students |>
  mutate(age = time_length(today() - birth_date, unit = "year")) |>
  group_by(group) |>
  summarise(median_age = round(median(age)))

median_age |>
  kable()
```

## Question 9 

```{r message=FALSE, warning=FALSE}
oldest <- students |>
  mutate(age = round(time_length(today() - birth_date, unit = "year"))) |>
  group_by(group) |>
  filter(age == max(age)) |>
  ungroup() |>
  arrange(desc(age)) |>
  select(id, group, sex, age)

oldest |>
  kable()
```

## Question 10

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)

nb_grades <- grades |>
  drop_na(grade) |>
  nrow()
```


The data set contains `r nb_grades` grades.

## Question 11

```{r message=FALSE, warning=FALSE}
cna_id <- courses |>
  filter(course == "Celestial Navigation and Astronomy") |>
  pull(course_id)

avg_cna <- students |>
  inner_join(grades, by = "id") |>
  filter(course_id == cna_id) |>
  group_by(group) |>
  summarise(mean_grade = mean(grade, na.rm = TRUE))

avg_cna |>
  ggplot(aes(x = group, y = mean_grade)) +
  geom_col()
```


